# https://github.com/poolshark-protocol/limit-sway/blob/abi-generation/libs/src/types/events.sw
name: Poolshark Indexer
networks:
  - id: 0
    start_block: 0
    contracts:
      - name: LimitPool
        address: 0x15ba5d06b9190c72b401f95bfac3522d0ddbb636db35542dfe4f07975f760fca
        abi_file_path: ./abis/limitpool-abi.json
        handler: ./src/EventHandlers.ts
        events:
          - name: InitPoolEvent
          - name: SwapEvent
          - name: MintLimitEvent
          - name: BurnLimitEvent
          - name: BurnRangeEvent
